### PR TITLE
New Commit, No horrible ness done

### PR DESCRIPTION
**Pull request by Budman17r**
screwed up my commit didn't want yours to end up screwy. I believe its good now. 

(It was all file locations)

### CODE REVIEW

**Comment by enkur** [comment]
Still showing the "This branch has conflicts that must be resolved" I am not sure what to do because if I click on Resolve conflicts button it takes me to a page with just the file contents and doesnt allow me anything else to do

**Comment by Gibby** [comment]
I wouldn't recommend merging this commit anyways. Look at the number of files submitted.  Hidden files and the env folder should not be submitted.

**Comment by enkur** [comment]
stupid question but how do I pull down this branch.

**Comment by Gibby** [comment]
@enkur look here https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by Budman17r** [comment]
Let me fix it.  And resubmit

**Comment by Budman17r** [comment]
Should be gtg now.

**Comment by war59312** [comment]
@Budman17r  What's up with the blank lines in address.py before "MAIN BODY" ?

Just curious the reasoning.

**Pull request merged**
